name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify:
    uses: basel5001/githubinfra/.github/workflows/release-notify.yml@main
    with:
      notify-type: discord
      message: "**New Release:** ${{ github.event.release.name }} - ${{ github.event.release.body }}"
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK }}

  homebrew:
    runs-on: ubuntu-latest
    needs: notify
    permissions:
      contents: read
    steps:
      - name: Update Homebrew Cask
        uses: macauley/action-homebrew-bump-cask@v1
        with:
          token: ${{ secrets.BREW_TOKEN }}
          org: Whisky-App
          cask: whisky
