name: SwiftLint

concurrency:
  group: pr-checks-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  SwiftLint:
    uses: basel5001/githubinfra/.github/workflows/linting.yml@main
    with:
      linter: swiftlint
      extra-args: ""
